drivers/block: hybridswap: fix type specifier missing in variable declarations
../drivers/block/zram/hybridswap/hybridswap_stats.c:344:15: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  344 | static inline meminfo_show(struct hybridswap_stat *stat, char *buf, ssize_t len)
      | ~~~~~~~~~~~~~ ^
      | int
1 error generated.