kernel/sched: eas_plus: fix type specifier missing in variable declarations
../kernel/sched/extension/eas_plus.c:295:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  295 | extern oplus_task_sched_boost(struct task_struct *p, int *task_prefer);
      | ~~~~~~ ^
      | int

1 error generated.